import Footer from "./Footer";
import Imgviewer from "./imgviewer";
import WhyKRP from "./WhyKRP";
import Navbar from "./Navbar/Navbar";
import Review from "./Review";
import News from "./News";
import Shopping from "./Shopping/Shopping";
import Info from "./Info";
import Subscribe from "./Subscribe";
import Article from "./Article";
export { Article, Subscribe, Shopping, News, WhyKRP, Review, Navbar, Footer, Imgviewer, Info };
